networks:
  default:
    name: vroomly
    external: true

volumes:
  vroomly-postgres-data:
    external: true


services:
  db:
    image: postgres:17.4
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${EXPOSE_DB_PORT:-5432}:5432
    volumes:
      - vroomly-postgres-data:/var/lib/postgresql/data:rw
    networks:
      default:
        aliases: [ vroomly-db ]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G

  backend:
    build: .
    env_file: .env
    volumes:
      - &app .:/app:rw
    ports:
      - ${EXPOSE_BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}
    depends_on:
      - db
    restart: unless-stopped
    profiles: [ vr-frontend ]
    networks:
      default:
        aliases: [ vroomly-backend ]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    command: ["uv", "run", "python", "/app/main.py"]

  migrations:
    build: .
    command: uv run alembic upgrade head
    env_file: .env
    volumes:
      - *app
    depends_on:
      - db
    restart: no
    profiles: [ vr-frontend ]
