services:
  db:
    image: postgres:17.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      default:
        aliases: [ habit-tracker-db ]

  backend:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${BACKEND_PORT:-8000}:8000
    depends_on:
      - db
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      default:
        aliases: [ habit-tracker-backend ]
    profiles: [ ht-frontend ]
