services:
  db:
    image: postgres:17.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${BACKEND_PORT:-8000}:8000
    depends_on:
      - db
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=5432
    restart: unless-stopped
    networks:
      - app-network
    profiles: [ ht-frontend ]

  migrations:
    build: .
    command: alembic upgrade head
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=5432
    restart: no
    networks:
      - app-network
    profiles: [ ht-frontend ]


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge