"""init tables

Revision ID: 27f0a46cd2b5
Revises: cc595d2d9f77
Create Date: 2025-08-23 17:18:47.273785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27f0a46cd2b5"
down_revision: Union[str, None] = "cc595d2d9f77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
        schema="accounts",
    )
    op.create_table(
        "country",
        sa.Column("id", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("short_name"),
        schema="geo",
    )
    op.create_table(
        "vehicle_engine",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("power", sa.SmallInteger(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_brand",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country_id", sa.String(length=3), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("original_name", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["geo.country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "country_id", "code", name="vehicle_brand_country_id_code_unique"
        ),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_group",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_model",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("vehicle_type", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["vehicles.vehicle_brand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_generation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_restyling", sa.Boolean(), nullable=False),
        sa.Column("start_year", sa.SmallInteger(), nullable=False),
        sa.Column("end_year", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["vehicles.vehicle_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_generation", schema="vehicles")
    op.drop_table("vehicle_model", schema="vehicles")
    op.drop_table("vehicle_group", schema="vehicles")
    op.drop_table("vehicle_brand", schema="vehicles")
    op.drop_table("vehicle_engine", schema="vehicles")
    op.drop_table("country", schema="geo")
    op.drop_table("user", schema="accounts")
    # ### end Alembic commands ###
