"""set users.birth_date nullable

Revision ID: b2a8cddbb558
Revises: 6e407478690a
Create Date: 2025-05-19 16:36:02.083181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2a8cddbb558"
down_revision: Union[str, None] = "6e407478690a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "birth_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "birth_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
