from apps.vehicles.models.car.enums import CarDriveType
from apps.vehicles.models.vehicle.enums import (
	VehicleEngineGRMType,
	VehicleEnginePhaseRegulatorType,
    VehicleTransmissionType,
)

phase_regulator_mapper = {
	'есть': VehicleEnginePhaseRegulatorType.INPUT,
	'впуск': VehicleEnginePhaseRegulatorType.INPUT,
	'на впуске': VehicleEnginePhaseRegulatorType.INPUT,
	'на впуске *': VehicleEnginePhaseRegulatorType.INPUT,
	'только на впуске': VehicleEnginePhaseRegulatorType.INPUT,
	'на впускном валу': VehicleEnginePhaseRegulatorType.INPUT,
	'на впускных валах': VehicleEnginePhaseRegulatorType.INPUT,
	'упр. натяжитель': VehicleEnginePhaseRegulatorType.INPUT,
	'выпуск': VehicleEnginePhaseRegulatorType.OUTPUT,
	'на выпуске': VehicleEnginePhaseRegulatorType.OUTPUT,
	'на выпускном валу': VehicleEnginePhaseRegulatorType.OUTPUT,
	'впуск + выпуск': VehicleEnginePhaseRegulatorType.DUAL,
	'впуск/выпуск': VehicleEnginePhaseRegulatorType.DUAL,
	'впуск / выпуск': VehicleEnginePhaseRegulatorType.DUAL,
	'на впуске и выпуске': VehicleEnginePhaseRegulatorType.DUAL,
	'на впуске и на выпуске': VehicleEnginePhaseRegulatorType.DUAL,
	'на всех валах': VehicleEnginePhaseRegulatorType.DUAL,
	'на обоих валах': VehicleEnginePhaseRegulatorType.DUAL,
	'на двух валах': VehicleEnginePhaseRegulatorType.DUAL,
	'гнц': VehicleEnginePhaseRegulatorType.COMPLEX,
	'с 2009 года': VehicleEnginePhaseRegulatorType.DUAL,
	'с 1999 года': VehicleEnginePhaseRegulatorType.DUAL,
	'опция': VehicleEnginePhaseRegulatorType.DUAL,
	'(опция)': VehicleEnginePhaseRegulatorType.DUAL,
}
phase_regulator_system_mapper: dict[str, str] = {
	# Honda
	'VTEC (на 150 л.с.)': 'VTEC',
	'VTEC (на 200 л.с.)': 'VTEC',
	'DVCT': 'DOHC_VTEC',
	'Dual-VCT': 'DOHC_VTEC',
	'Dual-VCT + VTEC': 'DOHC_VTEC',
	'Dual-VCT + i-VTEC': 'I_VTEC_AND_DOHC_VTEC',
	'Dual-VCT + i-VTEC *': 'I_VTEC_AND_DOHC_VTEC',
	'DVTC': 'DOHC_VTEC',
	'Dual-VTC': 'DOHC_VTEC',
	'Dual-VTC + VTEC': 'DOHC_VTEC',
	'Dual-VTC + i-VTEC': 'I_VTEC_AND_DOHC_VTEC',
	'Dual-VTC + i-VTEC *': 'I_VTEC_AND_DOHC_VTEC',
	'VCT + i-VTEC': 'I_VTEC_AND_VTC',
	'VCT и i-VTEC': 'I_VTEC_AND_VTC',
	'VTC + i-VTEC': 'I_VTEC_AND_VTC',
	# BMW
	'single VANOS': 'VANOS',
	'VANOS': 'VANOS',
	'dual-VANOS': 'DOUBLE_VANOS',
	'double VANOS': 'DOUBLE_VANOS',
	# Mitsubishi
	'MIVEC': 'MIVEC',
	'MIVEC 2': 'MIVEC',
	'опция': 'MIVEC',
	'опция MIVEC': 'MIVEC',
	'опция AVCS': 'AVCS',
	'eVTC': 'E_VTC',
	# Toyota
	'VVT-i с 2013 года': 'VVT_I',
	# Suzuki
	'(опция)': 'VVT',
}
grm_drive_type_mapper = {
	'ремень': VehicleEngineGRMType.BELT,
	'зубчатый ремень': VehicleEngineGRMType.BELT,
	'ременной': VehicleEngineGRMType.BELT,
	'два ремня': VehicleEngineGRMType.TWO_BELTS,
	'цепь': VehicleEngineGRMType.CHAIN,
	'цепной': VehicleEngineGRMType.CHAIN,
	'шестерни': VehicleEngineGRMType.GEARS,
	'шестеренчатый': VehicleEngineGRMType.GEARS,
	'однорядная цепь': VehicleEngineGRMType.CHAIN,
	'цепь морзе': VehicleEngineGRMType.CHAIN,
	'двухрядная цепь': VehicleEngineGRMType.TWO_CHAINS,
	'пара цепей': VehicleEngineGRMType.TWO_CHAINS,
	'цепь двухрядная': VehicleEngineGRMType.TWO_CHAINS,
	'ремень и цепь': VehicleEngineGRMType.BELT | VehicleEngineGRMType.CHAIN,
	'ремень плюс цепь': VehicleEngineGRMType.BELT | VehicleEngineGRMType.CHAIN,
	'ремень + цепь': VehicleEngineGRMType.BELT | VehicleEngineGRMType.CHAIN,
	'цепь и ремень': VehicleEngineGRMType.BELT | VehicleEngineGRMType.CHAIN,
	'ремень и цепи': VehicleEngineGRMType.BELT | VehicleEngineGRMType.TWO_CHAINS,
	'ремень и 2 цепи': VehicleEngineGRMType.BELT | VehicleEngineGRMType.TWO_CHAINS,
	'ремень и две цепи': VehicleEngineGRMType.BELT | VehicleEngineGRMType.TWO_CHAINS,
	'ремень и пара цепей': VehicleEngineGRMType.BELT | VehicleEngineGRMType.TWO_CHAINS,
	'две цепи': VehicleEngineGRMType.TWO_CHAINS,
	'три цепи': VehicleEngineGRMType.THREE_CHAINS,
	'цепь и шестерни': VehicleEngineGRMType.CHAIN | VehicleEngineGRMType.GEARS,
	'цепь/шестерни': VehicleEngineGRMType.CHAIN | VehicleEngineGRMType.GEARS,
	'ремень и шестерни': VehicleEngineGRMType.BELT | VehicleEngineGRMType.GEARS,
	'4 цепи': VehicleEngineGRMType.FOUR_CHAINS,
	'четыре цепи': VehicleEngineGRMType.FOUR_CHAINS,
}
transmission_type_mapper = {
	'механика': VehicleTransmissionType.MANUAL,
	'механическая коробка': VehicleTransmissionType.MANUAL,
	'мкпп': VehicleTransmissionType.MANUAL,
	'автомат': VehicleTransmissionType.AUTO,
	'гибридный автомат': VehicleTransmissionType.AUTO,
	'гидроавтомат': VehicleTransmissionType.AUTO,
	'гидроавтомат + dct': VehicleTransmissionType.AUTO,
	'акпп': VehicleTransmissionType.AUTO,
	'вариатор': VehicleTransmissionType.VARIATOR,
	'cvt': VehicleTransmissionType.VARIATOR,
	'робот': VehicleTransmissionType.ROBOT,
	'роботизированная': VehicleTransmissionType.ROBOT,
	'роботизированная коробка': VehicleTransmissionType.ROBOT,
	'dct': VehicleTransmissionType.ROBOT,
	'однодисковый робот': VehicleTransmissionType.ROBOT,
	'преселективный робот': VehicleTransmissionType.ROBOT,
}
transmission_drive_type_mapper = {
	'передний': CarDriveType.FRONT,
	'задний': CarDriveType.BACK,
	'полный': CarDriveType.FULL,
}
