export { Button } from './components/Button';
export { TextInput } from './components/TextInput';
export { PasswordInput } from './components/PasswordInput';
export { NumberInput } from './components/NumberInput';
export { Select } from './components/Select';
export { Switch } from './components/Switch';
export { Container } from './components/Container';
export { Paper } from './components/Paper';
export { Stack } from './components/Stack';
export { Flex } from './components/Flex';
export { Text } from './components/Text';
export { Title } from './components/Title';
export { ActionIcon } from './components/ActionIcon';
export { Tooltip } from './components/Tooltip';
export { Indicator } from './components/Indicator';
export { DatePickerInput } from './components/DatePickerInput';
export { Tabs, TabContent } from './components/Tabs';

export { UIProvider } from './context/UIProvider';
export { useUIRegistry } from './context/UIProvider';
export { useUIComponent } from './context/useUIComponent';
export { defaultComponents } from './registry';
export type { ComponentRegistry, ComponentName } from './registry';

export type { ButtonProps } from './components/Button';
export type { TextInputProps } from './components/TextInput';
export type { PasswordInputProps } from './components/PasswordInput';
export type { NumberInputProps } from './components/NumberInput';
export type { SelectProps, SelectOption } from './components/Select';
export type { SwitchProps } from './components/Switch';
export type { ContainerProps } from './components/Container';
export type { PaperProps } from './components/Paper';
export type { StackProps } from './components/Stack';
export type { FlexProps } from './components/Flex';
export type { TextProps } from './components/Text';
export type { TitleProps } from './components/Title';
export type { ActionIconProps } from './components/ActionIcon';
export type { TooltipProps } from './components/Tooltip';
export type { IndicatorProps } from './components/Indicator';
export type { DatePickerInputProps } from './components/DatePickerInput';
export type { TabsProps, TabContentProps, TabItem } from './components/Tabs/index';
