"""init vehicle models

Revision ID: 1731e4b3cb70
Revises: 27f0a46cd2b5
Create Date: 2025-09-29 18:35:26.877671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1731e4b3cb70"
down_revision: Union[str, None] = "27f0a46cd2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "car_body",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("trunk_volume", sa.SmallInteger(), nullable=True),
        sa.Column("material", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "car_transmission",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("drive_type", sa.SmallInteger(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("gears", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "motorcycle_body",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("seat_height", sa.SmallInteger(), nullable=True),
        sa.Column("material", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "motorcycle_transmission",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("shift_type", sa.SmallInteger(), nullable=False),
        sa.Column("slipper_clutch", sa.Boolean(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("gears", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_engine",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("displacement", sa.SmallInteger(), nullable=False),
        sa.Column("power", sa.SmallInteger(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "car_engine_spec",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("eco_class", sa.String(length=50), nullable=False),
        sa.Column("cylinders", sa.SmallInteger(), nullable=False),
        sa.Column("is_turbo", sa.Boolean(), nullable=False),
        sa.Column("engine_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engine_id"],
            ["vehicles.vehicle_engine.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "motorcycle_engine_spec",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooling", sa.SmallInteger(), nullable=False),
        sa.Column("stroke", sa.SmallInteger(), nullable=False),
        sa.Column("cylinders", sa.SmallInteger(), nullable=False),
        sa.Column("engine_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engine_id"],
            ["vehicles.vehicle_engine.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vehicle_type", sa.SmallInteger(), nullable=False),
        sa.Column("production_year", sa.SmallInteger(), nullable=False),
        sa.Column("color", sa.String(length=100), nullable=True),
        sa.Column("country_id", sa.String(length=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["geo.country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_brand",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("original_name", sa.String(length=50), nullable=True),
        sa.Column("country_id", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["geo.country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "country_id", "code", name="vehicle_brand_country_id_code_unique"
        ),
        schema="vehicles",
    )
    op.create_table(
        "user_vehicle",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("is_mileage_in_miles", sa.Boolean(), nullable=False),
        sa.Column(
            "avg_fuel_consumption", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_group",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_series",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("vehicle_type", sa.SmallInteger(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["vehicles.vehicle_brand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "vehicle_generation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_restyling", sa.Boolean(), nullable=False),
        sa.Column("start_year", sa.SmallInteger(), nullable=False),
        sa.Column("end_year", sa.SmallInteger(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["vehicles.vehicle_series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "car_spec",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=False),
        sa.Column("body_number", sa.String(length=50), nullable=True),
        sa.Column("number", sa.String(length=50), nullable=True),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["vehicles.vehicle_generation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "car_trim",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "avg_fuel_consumption", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column("acceleration", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("clearance", sa.SmallInteger(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engine_id", sa.UUID(), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engine_id"],
            ["vehicles.vehicle_engine.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["vehicles.vehicle_generation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "motorcycle_spec",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["vehicles.vehicle_generation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.create_table(
        "motorcycle_trim",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engine_id", sa.UUID(), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engine_id"],
            ["vehicles.vehicle_engine.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["vehicles.vehicle_generation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="vehicles",
    )
    op.add_column(
        "user",
        sa.Column("country_id", sa.String(length=3), nullable=True),
        schema="accounts",
    )
    op.create_foreign_key(
        None,
        "user",
        "country",
        ["country_id"],
        ["id"],
        source_schema="accounts",
        referent_schema="geo",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", schema="accounts", type_="foreignkey")
    op.drop_column("user", "country_id", schema="accounts")
    op.drop_table("motorcycle_trim", schema="vehicles")
    op.drop_table("motorcycle_spec", schema="vehicles")
    op.drop_table("car_trim", schema="vehicles")
    op.drop_table("car_spec", schema="vehicles")
    op.drop_table("vehicle_generation", schema="vehicles")
    op.drop_table("vehicle_series", schema="vehicles")
    op.drop_table("vehicle_group", schema="vehicles")
    op.drop_table("user_vehicle", schema="vehicles")
    op.drop_table("vehicle_brand", schema="vehicles")
    op.drop_table("vehicle", schema="vehicles")
    op.drop_table("motorcycle_engine_spec", schema="vehicles")
    op.drop_table("car_engine_spec", schema="vehicles")
    op.drop_table("vehicle_engine", schema="vehicles")
    op.drop_table("motorcycle_transmission", schema="vehicles")
    op.drop_table("motorcycle_body", schema="vehicles")
    op.drop_table("car_transmission", schema="vehicles")
    op.drop_table("car_body", schema="vehicles")
    # ### end Alembic commands ###
