"""step 13 m2m group user_vehicle

Revision ID: 2d0c4b831eae
Revises: 822d8cec7482
Create Date: 2026-05-27 14:45:44.618822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0c4b831eae'
down_revision: Union[str, None] = '822d8cec7482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vehicle_group_link',
    sa.Column('user_vehicle_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['vehicles.vehicle_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['vehicles.user_vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_vehicle_id', 'group_id'),
    schema='vehicles'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vehicle_group_link', schema='vehicles')
    # ### end Alembic commands ###
