"""add name to vehicle body abstract

Revision ID: 301b0013d22c
Revises: 9e37921b4bff
Create Date: 2025-10-19 21:46:35.472278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "301b0013d22c"
down_revision: Union[str, None] = "9e37921b4bff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "car_body",
        sa.Column("name", sa.String(length=50), nullable=True),
        schema="vehicles",
    )
    op.add_column(
        "motorcycle_body",
        sa.Column("name", sa.String(length=50), nullable=True),
        schema="vehicles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("motorcycle_body", "name", schema="vehicles")
    op.drop_column("car_body", "name", schema="vehicles")
    # ### end Alembic commands ###
