"""extend vehicle engine and delete specs

Revision ID: 39ae9a01a7e7
Revises: 725c1c6badff
Create Date: 2025-10-23 16:24:20.590093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ae9a01a7e7'
down_revision: Union[str, None] = '725c1c6badff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_transmission', sa.Column('drive_types', sa.ARRAY(sa.SmallInteger()), nullable=False), schema='vehicles')
    op.add_column('car_transmission', sa.Column('brand_id', sa.UUID(), nullable=False), schema='vehicles')
    op.create_unique_constraint('car_transmission_brand_id_name_unique', 'car_transmission', ['brand_id', 'name'], schema='vehicles')
    op.create_foreign_key(None, 'car_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_column('car_transmission', 'drive_type', schema='vehicles')
    op.add_column('motorcycle_transmission', sa.Column('brand_id', sa.UUID(), nullable=False), schema='vehicles')
    op.create_unique_constraint('motorcycle_transmission_brand_id_name_unique', 'motorcycle_transmission', ['brand_id', 'name'], schema='vehicles')
    op.create_foreign_key(None, 'motorcycle_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.add_column('vehicle_brand', sa.Column('abbreviation', sa.String(length=6), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('phase_regulator_system', sa.String(length=50), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('brand_id', sa.UUID(), nullable=False), schema='vehicles')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_column('vehicle_engine', 'phase_regulator', schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_engine', sa.Column('phase_regulator', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='vehicles')
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_column('vehicle_engine', 'brand_id', schema='vehicles')
    op.drop_column('vehicle_engine', 'phase_regulator_system', schema='vehicles')
    op.drop_column('vehicle_brand', 'abbreviation', schema='vehicles')
    op.drop_constraint(None, 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint('motorcycle_transmission_brand_id_name_unique', 'motorcycle_transmission', schema='vehicles', type_='unique')
    op.drop_column('motorcycle_transmission', 'brand_id', schema='vehicles')
    op.add_column('car_transmission', sa.Column('drive_type', sa.SMALLINT(), autoincrement=False, nullable=False), schema='vehicles')
    op.drop_constraint(None, 'car_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint('car_transmission_brand_id_name_unique', 'car_transmission', schema='vehicles', type_='unique')
    op.drop_column('car_transmission', 'brand_id', schema='vehicles')
    op.drop_column('car_transmission', 'drive_types', schema='vehicles')
    # ### end Alembic commands ###
