"""extend vehicle engine phase_regulator

Revision ID: 3f4294d99d27
Revises: 39ae9a01a7e7
Create Date: 2025-10-23 16:25:01.158826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4294d99d27'
down_revision: Union[str, None] = '39ae9a01a7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_engine', sa.Column('phase_regulator', sa.SmallInteger(), nullable=True), schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_engine', 'phase_regulator', schema='vehicles')
    # ### end Alembic commands ###
