"""migration

Revision ID: 4be344cebdd3
Revises: ddb4fd70080c
Create Date: 2026-05-20 11:27:05.768024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be344cebdd3'
down_revision: Union[str, None] = 'ddb4fd70080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_trim', sa.Column('drive_type', sa.SmallInteger(), nullable=True), schema='vehicles')
    op.add_column('car_trim', sa.Column('body_str', sa.String(length=50), nullable=True), schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_trim', 'body_str', schema='vehicles')
    op.drop_column('car_trim', 'drive_type', schema='vehicles')
    # ### end Alembic commands ###
