"""remove car_trim drive_type and body_str

Revision ID: 4f43d74dc3d1
Revises: eadcdf7ec004
Create Date: 2026-05-21 20:09:45.474372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f43d74dc3d1'
down_revision: Union[str, None] = 'eadcdf7ec004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_trim', 'body_str', schema='vehicles')
    op.drop_column('car_trim', 'drive_type', schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_trim', sa.Column('drive_type', sa.SMALLINT(), autoincrement=False, nullable=True), schema='vehicles')
    op.add_column('car_trim', sa.Column('body_str', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='vehicles')
    # ### end Alembic commands ###
