"""extend engine model

Revision ID: 725c1c6badff
Revises: 301b0013d22c
Create Date: 2025-10-21 20:16:03.929773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725c1c6badff'
down_revision: Union[str, None] = '301b0013d22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motorcycle_engine_spec', schema='vehicles')
    op.drop_table('car_engine_spec', schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('volume', sa.SmallInteger(), nullable=False), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('eco_class', sa.String(length=50), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('cylinders', sa.SmallInteger(), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('valves', sa.SmallInteger(), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('torque', sa.SmallInteger(), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('grm_drive_type', sa.SmallInteger(), nullable=False), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('phase_regulator', sa.Boolean(), nullable=True), schema='vehicles')
    op.drop_column('vehicle_engine', 'displacement', schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_engine', sa.Column('displacement', sa.SMALLINT(), autoincrement=False, nullable=False), schema='vehicles')
    op.drop_column('vehicle_engine', 'phase_regulator', schema='vehicles')
    op.drop_column('vehicle_engine', 'grm_drive_type', schema='vehicles')
    op.drop_column('vehicle_engine', 'torque', schema='vehicles')
    op.drop_column('vehicle_engine', 'valves', schema='vehicles')
    op.drop_column('vehicle_engine', 'cylinders', schema='vehicles')
    op.drop_column('vehicle_engine', 'eco_class', schema='vehicles')
    op.drop_column('vehicle_engine', 'volume', schema='vehicles')
    op.create_table('car_engine_spec',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('eco_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cylinders', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('valves', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['vehicles.vehicle_engine.id'], name=op.f('car_engine_spec_engine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('car_engine_spec_pkey')),
    schema='vehicles'
    )
    op.create_table('motorcycle_engine_spec',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cooling', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('stroke', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('cylinders', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('engine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['vehicles.vehicle_engine.id'], name=op.f('motorcycle_engine_spec_engine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('motorcycle_engine_spec_pkey')),
    schema='vehicles'
    )
    # ### end Alembic commands ###
