"""add relations to car and moto trim

Revision ID: 7e6a42a45a2e
Revises: 59a348d2deef
Create Date: 2025-10-19 21:29:04.430721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e6a42a45a2e"
down_revision: Union[str, None] = "59a348d2deef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "car_body",
        "material",
        existing_type=sa.SMALLINT(),
        nullable=True,
        schema="vehicles",
    )
    op.add_column(
        "car_transmission",
        sa.Column("name", sa.String(length=50), nullable=False),
        schema="vehicles",
    )
    op.add_column(
        "car_trim",
        sa.Column("transmission_id", sa.UUID(), nullable=False),
        schema="vehicles",
    )
    op.add_column(
        "car_trim", sa.Column("body_id", sa.UUID(), nullable=False), schema="vehicles"
    )
    op.create_foreign_key(
        None,
        "car_trim",
        "car_transmission",
        ["transmission_id"],
        ["id"],
        source_schema="vehicles",
        referent_schema="vehicles",
    )
    op.create_foreign_key(
        None,
        "car_trim",
        "car_body",
        ["body_id"],
        ["id"],
        source_schema="vehicles",
        referent_schema="vehicles",
    )
    op.alter_column(
        "motorcycle_body",
        "material",
        existing_type=sa.SMALLINT(),
        nullable=True,
        schema="vehicles",
    )
    op.add_column(
        "motorcycle_transmission",
        sa.Column("name", sa.String(length=50), nullable=False),
        schema="vehicles",
    )
    op.add_column(
        "motorcycle_trim",
        sa.Column("transmission_id", sa.UUID(), nullable=False),
        schema="vehicles",
    )
    op.add_column(
        "motorcycle_trim",
        sa.Column("body_id", sa.UUID(), nullable=False),
        schema="vehicles",
    )
    op.create_foreign_key(
        None,
        "motorcycle_trim",
        "motorcycle_body",
        ["body_id"],
        ["id"],
        source_schema="vehicles",
        referent_schema="vehicles",
    )
    op.create_foreign_key(
        None,
        "motorcycle_trim",
        "motorcycle_transmission",
        ["transmission_id"],
        ["id"],
        source_schema="vehicles",
        referent_schema="vehicles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "motorcycle_trim", schema="vehicles", type_="foreignkey")
    op.drop_constraint(None, "motorcycle_trim", schema="vehicles", type_="foreignkey")
    op.drop_column("motorcycle_trim", "body_id", schema="vehicles")
    op.drop_column("motorcycle_trim", "transmission_id", schema="vehicles")
    op.drop_column("motorcycle_transmission", "name", schema="vehicles")
    op.alter_column(
        "motorcycle_body",
        "material",
        existing_type=sa.SMALLINT(),
        nullable=False,
        schema="vehicles",
    )
    op.drop_constraint(None, "car_trim", schema="vehicles", type_="foreignkey")
    op.drop_constraint(None, "car_trim", schema="vehicles", type_="foreignkey")
    op.drop_column("car_trim", "body_id", schema="vehicles")
    op.drop_column("car_trim", "transmission_id", schema="vehicles")
    op.drop_column("car_transmission", "name", schema="vehicles")
    op.alter_column(
        "car_body",
        "material",
        existing_type=sa.SMALLINT(),
        nullable=False,
        schema="vehicles",
    )
    # ### end Alembic commands ###
