"""step 11 unique indexes

Revision ID: 822d8cec7482
Revises: f94b26d2a4b6
Create Date: 2026-05-27 14:43:31.058228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822d8cec7482'
down_revision: Union[str, None] = 'f94b26d2a4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('car_spec_vin_unique', 'car_spec', ['vin'], schema='vehicles')
    op.create_index('vehicle_engine_brand_id_name_unique', 'vehicle_engine', ['brand_id', 'name'], unique=True, schema='vehicles', postgresql_where=sa.text('brand_id IS NOT NULL'))
    op.create_index('vehicle_engine_concern_id_name_unique', 'vehicle_engine', ['concern_id', 'name'], unique=True, schema='vehicles', postgresql_where=sa.text('concern_id IS NOT NULL'))
    op.create_unique_constraint('vehicle_generation_series_name_restyling_unique', 'vehicle_generation', ['series_id', 'name', 'is_restyling'], schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehicle_generation_series_name_restyling_unique', 'vehicle_generation', schema='vehicles', type_='unique')
    op.drop_index('vehicle_engine_concern_id_name_unique', table_name='vehicle_engine', schema='vehicles', postgresql_where=sa.text('concern_id IS NOT NULL'))
    op.drop_index('vehicle_engine_brand_id_name_unique', table_name='vehicle_engine', schema='vehicles', postgresql_where=sa.text('brand_id IS NOT NULL'))
    op.drop_constraint('car_spec_vin_unique', 'car_spec', schema='vehicles', type_='unique')
    # ### end Alembic commands ###
