"""add vehicle_concern model

Revision ID: 959adf52ced8
Revises: 3f4294d99d27
Create Date: 2025-10-23 17:52:29.591293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959adf52ced8'
down_revision: Union[str, None] = '3f4294d99d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_concern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=6), nullable=True),
    sa.Column('country_id', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['geo.country.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.drop_constraint(op.f('user_country_id_fkey'), 'user', schema='accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'], source_schema='accounts', referent_schema='geo', ondelete='SET NULL')
    op.add_column('car_transmission', sa.Column('concern_id', sa.UUID(), nullable=True), schema='vehicles')
    op.alter_column('car_transmission', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='vehicles')
    op.drop_constraint(op.f('car_transmission_brand_id_name_unique'), 'car_transmission', schema='vehicles', type_='unique')
    op.drop_constraint(op.f('car_transmission_brand_id_fkey'), 'car_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'car_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(None, 'car_transmission', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(op.f('vehicle_country_id_fkey'), 'vehicle', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo', ondelete='SET NULL')
    op.add_column('vehicle_brand', sa.Column('concern_id', sa.UUID(), nullable=True), schema='vehicles')
    op.create_foreign_key(None, 'vehicle_brand', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.add_column('vehicle_engine', sa.Column('concern_id', sa.UUID(), nullable=True), schema='vehicles')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_column('vehicle_engine', 'concern_id', schema='vehicles')
    op.drop_constraint(None, 'vehicle_brand', schema='vehicles', type_='foreignkey')
    op.drop_column('vehicle_brand', 'concern_id', schema='vehicles')
    op.drop_constraint(None, 'vehicle', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_country_id_fkey'), 'vehicle', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo')
    op.drop_constraint(None, 'car_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'car_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('car_transmission_brand_id_fkey'), 'car_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_unique_constraint(op.f('car_transmission_brand_id_name_unique'), 'car_transmission', ['brand_id', 'name'], schema='vehicles', postgresql_nulls_not_distinct=False)
    op.alter_column('car_transmission', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='vehicles')
    op.drop_column('car_transmission', 'concern_id', schema='vehicles')
    op.drop_constraint(None, 'user', schema='accounts', type_='foreignkey')
    op.create_foreign_key(op.f('user_country_id_fkey'), 'user', 'country', ['country_id'], ['id'], source_schema='accounts', referent_schema='geo')
    op.drop_table('vehicle_concern', schema='vehicles')
    # ### end Alembic commands ###
