"""change motorcycle transmission fk-s

Revision ID: 9ce11073c8a2
Revises: 959adf52ced8
Create Date: 2025-10-23 22:19:10.275720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce11073c8a2'
down_revision: Union[str, None] = '959adf52ced8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycle_transmission', sa.Column('concern_id', sa.UUID(), nullable=True), schema='vehicles')
    op.alter_column('motorcycle_transmission', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='vehicles')
    op.drop_constraint(op.f('motorcycle_transmission_brand_id_name_unique'), 'motorcycle_transmission', schema='vehicles', type_='unique')
    op.drop_constraint(op.f('motorcycle_transmission_brand_id_fkey'), 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'motorcycle_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(None, 'motorcycle_transmission', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('motorcycle_transmission_brand_id_fkey'), 'motorcycle_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_unique_constraint(op.f('motorcycle_transmission_brand_id_name_unique'), 'motorcycle_transmission', ['brand_id', 'name'], schema='vehicles', postgresql_nulls_not_distinct=False)
    op.alter_column('motorcycle_transmission', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='vehicles')
    op.drop_column('motorcycle_transmission', 'concern_id', schema='vehicles')
    # ### end Alembic commands ###
