"""add torgue to car transmission

Revision ID: 9e37921b4bff
Revises: 7e6a42a45a2e
Create Date: 2025-10-19 21:41:28.926020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e37921b4bff"
down_revision: Union[str, None] = "7e6a42a45a2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "car_transmission",
        sa.Column("torque", sa.SmallInteger(), nullable=True),
        schema="vehicles",
    )
    op.add_column(
        "car_transmission",
        sa.Column("index", sa.String(length=50), nullable=True),
        schema="vehicles",
    )
    op.add_column(
        "motorcycle_transmission",
        sa.Column("index", sa.String(length=50), nullable=True),
        schema="vehicles",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("motorcycle_transmission", "index", schema="vehicles")
    op.drop_column("car_transmission", "index", schema="vehicles")
    op.drop_column("car_transmission", "torque", schema="vehicles")
    # ### end Alembic commands ###
