"""unify vehicle nodes (JTI) + user_vehicle_node + reminder m2m

Revision ID: beaf2f8564a1
Revises: e057f8de8cb7
Create Date: 2026-05-29 09:47:38.728579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beaf2f8564a1'
down_revision: Union[str, None] = 'e057f8de8cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_table('car_body_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('trunk_volume', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('material', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['vehicles.vehicle_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_table('motorcycle_body_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('seat_height', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('material', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['vehicles.vehicle_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_table('car_transmission_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_types', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('torque', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('index', sa.String(length=50), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('gears', sa.SmallInteger(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('concern_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('brand_id IS NOT NULL OR concern_id IS NOT NULL', name='car_transmission_node_brand_or_concern_required'),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['vehicles.vehicle_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_index('car_transmission_node_brand_type_gears_name_unique', 'car_transmission_node', ['brand_id', 'type', 'gears', 'name'], unique=True, schema='vehicles', postgresql_where=sa.text('brand_id IS NOT NULL'))
    op.create_index('car_transmission_node_concern_type_gears_name_unique', 'car_transmission_node', ['concern_id', 'type', 'gears', 'name'], unique=True, schema='vehicles', postgresql_where=sa.text('concern_id IS NOT NULL'))
    op.create_table('motorcycle_transmission_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_type', sa.SmallInteger(), nullable=False),
    sa.Column('slipper_clutch', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('index', sa.String(length=50), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('gears', sa.SmallInteger(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('concern_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('brand_id IS NOT NULL OR concern_id IS NOT NULL', name='motorcycle_transmission_node_brand_or_concern_required'),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['vehicles.vehicle_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_table('user_vehicle_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_vehicle_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['vehicles.user_vehicle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_node_id'], ['vehicles.vehicle_node.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_vehicle_id', 'vehicle_node_id', name='user_vehicle_node_unique'),
    schema='vehicles'
    )
    op.create_table('engine_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.SmallInteger(), nullable=False),
    sa.Column('power', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('eco_class', sa.String(length=50), nullable=True),
    sa.Column('cylinders', sa.SmallInteger(), nullable=True),
    sa.Column('valves', sa.SmallInteger(), nullable=True),
    sa.Column('torque', sa.SmallInteger(), nullable=True),
    sa.Column('grm_drive_type', sa.SmallInteger(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('concern_id', sa.UUID(), nullable=True),
    sa.Column('phase_regulator_system_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('brand_id IS NOT NULL OR concern_id IS NOT NULL', name='engine_node_brand_or_concern_required'),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['vehicles.vehicle_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_regulator_system_id'], ['vehicles.vehicle_engine_phase_regulator_system.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_index('engine_node_brand_name_volume_power_unique', 'engine_node', ['brand_id', 'name', 'volume', 'power'], unique=True, schema='vehicles', postgresql_where=sa.text('brand_id IS NOT NULL'))
    op.create_index('engine_node_concern_name_volume_power_unique', 'engine_node', ['concern_id', 'name', 'volume', 'power'], unique=True, schema='vehicles', postgresql_where=sa.text('concern_id IS NOT NULL'))
    op.create_table('reminder_node_link',
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('user_vehicle_node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['vehicles.vehicle_reminder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_vehicle_node_id'], ['vehicles.user_vehicle_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', 'user_vehicle_node_id'),
    schema='vehicles'
    )

    # Переносим справочные данные из старых таблиц в JTI-узлы, сохраняя id,
    # чтобы существующие ссылки trim/spec остались валидными.
    # Двигатели: phase_regulator_type отбрасывается (живёт на фазорегуляторе).
    op.execute("""
        INSERT INTO vehicles.vehicle_node (id, node_type)
        SELECT id, 'engine' FROM vehicles.vehicle_engine
    """)
    op.execute("""
        INSERT INTO vehicles.engine_node (
            id, name, volume, power, type, eco_class, cylinders, valves, torque,
            grm_drive_type, brand_id, concern_id, phase_regulator_system_id
        )
        SELECT id, name, volume, power, type, eco_class, cylinders, valves, torque,
               grm_drive_type, brand_id, concern_id, phase_regulator_system_id
        FROM vehicles.vehicle_engine
    """)

    # Коробки передач автомобиля.
    op.execute("""
        INSERT INTO vehicles.vehicle_node (id, node_type)
        SELECT id, 'car_transmission' FROM vehicles.car_transmission
    """)
    op.execute("""
        INSERT INTO vehicles.car_transmission_node (
            id, name, index, type, gears, drive_types, torque, brand_id, concern_id
        )
        SELECT id, name, index, type, gears, drive_types, torque, brand_id, concern_id
        FROM vehicles.car_transmission
    """)

    # Коробки передач мотоцикла.
    op.execute("""
        INSERT INTO vehicles.vehicle_node (id, node_type)
        SELECT id, 'motorcycle_transmission' FROM vehicles.motorcycle_transmission
    """)
    op.execute("""
        INSERT INTO vehicles.motorcycle_transmission_node (
            id, name, index, type, gears, shift_type, slipper_clutch, brand_id, concern_id
        )
        SELECT id, name, index, type, gears, shift_type, slipper_clutch, brand_id, concern_id
        FROM vehicles.motorcycle_transmission
    """)

    # Кузова автомобиля.
    op.execute("""
        INSERT INTO vehicles.vehicle_node (id, node_type)
        SELECT id, 'car_body' FROM vehicles.car_body
    """)
    op.execute("""
        INSERT INTO vehicles.car_body_node (id, name, material, type, trunk_volume)
        SELECT id, name, material, type, trunk_volume FROM vehicles.car_body
    """)

    # Кузова мотоцикла.
    op.execute("""
        INSERT INTO vehicles.vehicle_node (id, node_type)
        SELECT id, 'motorcycle_body' FROM vehicles.motorcycle_body
    """)
    op.execute("""
        INSERT INTO vehicles.motorcycle_body_node (id, name, material, type, seat_height)
        SELECT id, name, material, type, seat_height FROM vehicles.motorcycle_body
    """)

    # Перенаправляем FK у trim/spec на новые узловые таблицы ДО удаления старых
    # таблиц (иначе drop_table упадёт из-за существующих ссылок).
    op.drop_constraint(op.f('car_spec_engine_id_fkey'), 'car_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_spec_transmission_id_fkey'), 'car_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('car_spec_engine_id_fkey', 'car_spec', 'engine_node', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key('car_spec_transmission_id_fkey', 'car_spec', 'car_transmission_node', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(op.f('car_trim_transmission_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_trim_body_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_trim_engine_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('car_trim_engine_id_fkey', 'car_trim', 'engine_node', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('car_trim_transmission_id_fkey', 'car_trim', 'car_transmission_node', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('car_trim_body_id_fkey', 'car_trim', 'car_body_node', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(op.f('motorcycle_spec_transmission_id_fkey'), 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_spec_engine_id_fkey'), 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('motorcycle_spec_transmission_id_fkey', 'motorcycle_spec', 'motorcycle_transmission_node', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key('motorcycle_spec_engine_id_fkey', 'motorcycle_spec', 'engine_node', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(op.f('motorcycle_trim_transmission_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_trim_engine_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_trim_body_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('motorcycle_trim_engine_id_fkey', 'motorcycle_trim', 'engine_node', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('motorcycle_trim_transmission_id_fkey', 'motorcycle_trim', 'motorcycle_transmission_node', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('motorcycle_trim_body_id_fkey', 'motorcycle_trim', 'motorcycle_body_node', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')

    # Теперь старые таблицы ни на что не ссылаются — можно удалять.
    op.drop_table('motorcycle_body', schema='vehicles')
    op.drop_index(op.f('car_transmission_brand_type_gears_name_unique'), table_name='car_transmission', schema='vehicles', postgresql_where='(brand_id IS NOT NULL)')
    op.drop_index(op.f('car_transmission_concern_type_gears_name_unique'), table_name='car_transmission', schema='vehicles', postgresql_where='(concern_id IS NOT NULL)')
    op.drop_table('car_transmission', schema='vehicles')
    op.drop_index(op.f('vehicle_engine_brand_name_volume_power_unique'), table_name='vehicle_engine', schema='vehicles', postgresql_where='(brand_id IS NOT NULL)')
    op.drop_index(op.f('vehicle_engine_concern_name_volume_power_unique'), table_name='vehicle_engine', schema='vehicles', postgresql_where='(concern_id IS NOT NULL)')
    op.drop_table('vehicle_engine', schema='vehicles')
    op.drop_table('car_body', schema='vehicles')
    op.drop_table('motorcycle_transmission', schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала пересоздаём старые таблицы, затем перенаправляем FK обратно на них,
    # и только потом удаляем узловые таблицы.
    op.create_table('motorcycle_transmission',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shift_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('slipper_clutch', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('gears', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('index', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concern_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('brand_id IS NOT NULL OR concern_id IS NOT NULL', name=op.f('motorcycle_transmission_brand_or_concern_required')),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], name=op.f('motorcycle_transmission_brand_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], name=op.f('motorcycle_transmission_concern_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('motorcycle_transmission_pkey')),
    schema='vehicles'
    )
    op.create_table('car_body',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('trunk_volume', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('material', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('car_body_pkey')),
    schema='vehicles'
    )
    op.create_table('vehicle_engine',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('power', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('eco_class', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cylinders', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('valves', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('torque', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('grm_drive_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concern_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phase_regulator_type', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('phase_regulator_system_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('brand_id IS NOT NULL OR concern_id IS NOT NULL', name=op.f('vehicle_engine_brand_or_concern_required')),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], name=op.f('vehicle_engine_brand_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], name=op.f('vehicle_engine_concern_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_regulator_system_id'], ['vehicles.vehicle_engine_phase_regulator_system.id'], name=op.f('vehicle_engine_phase_regulator_system_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_engine_pkey')),
    schema='vehicles'
    )
    op.create_index(op.f('vehicle_engine_concern_name_volume_power_unique'), 'vehicle_engine', ['concern_id', 'name', 'volume', 'power'], unique=True, schema='vehicles', postgresql_where='(concern_id IS NOT NULL)')
    op.create_index(op.f('vehicle_engine_brand_name_volume_power_unique'), 'vehicle_engine', ['brand_id', 'name', 'volume', 'power'], unique=True, schema='vehicles', postgresql_where='(brand_id IS NOT NULL)')
    op.create_table('car_transmission',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('gears', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('torque', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('index', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('drive_types', postgresql.ARRAY(sa.SMALLINT()), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('concern_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('brand_id IS NOT NULL OR concern_id IS NOT NULL', name=op.f('car_transmission_brand_or_concern_required')),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], name=op.f('car_transmission_brand_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], name=op.f('car_transmission_concern_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('car_transmission_pkey')),
    schema='vehicles'
    )
    op.create_index(op.f('car_transmission_concern_type_gears_name_unique'), 'car_transmission', ['concern_id', 'type', 'gears', 'name'], unique=True, schema='vehicles', postgresql_where='(concern_id IS NOT NULL)')
    op.create_index(op.f('car_transmission_brand_type_gears_name_unique'), 'car_transmission', ['brand_id', 'type', 'gears', 'name'], unique=True, schema='vehicles', postgresql_where='(brand_id IS NOT NULL)')
    op.create_table('motorcycle_body',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('seat_height', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('material', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('motorcycle_body_pkey')),
    schema='vehicles'
    )

    # Возвращаем справочные данные из узлов обратно в старые таблицы.
    # phase_regulator_type восстановить нельзя (он был отброшен при upgrade) —
    # ставим UNDEFINED (0).
    op.execute("""
        INSERT INTO vehicles.vehicle_engine (
            id, name, volume, power, type, eco_class, cylinders, valves, torque,
            grm_drive_type, brand_id, concern_id, phase_regulator_system_id, phase_regulator_type
        )
        SELECT id, name, volume, power, type, eco_class, cylinders, valves, torque,
               grm_drive_type, brand_id, concern_id, phase_regulator_system_id, 0
        FROM vehicles.engine_node
    """)
    op.execute("""
        INSERT INTO vehicles.car_transmission (
            id, name, index, type, gears, drive_types, torque, brand_id, concern_id
        )
        SELECT id, name, index, type, gears, drive_types, torque, brand_id, concern_id
        FROM vehicles.car_transmission_node
    """)
    op.execute("""
        INSERT INTO vehicles.motorcycle_transmission (
            id, name, index, type, gears, shift_type, slipper_clutch, brand_id, concern_id
        )
        SELECT id, name, index, type, gears, shift_type, slipper_clutch, brand_id, concern_id
        FROM vehicles.motorcycle_transmission_node
    """)
    op.execute("""
        INSERT INTO vehicles.car_body (id, name, material, type, trunk_volume)
        SELECT id, name, material, type, trunk_volume FROM vehicles.car_body_node
    """)
    op.execute("""
        INSERT INTO vehicles.motorcycle_body (id, name, material, type, seat_height)
        SELECT id, name, material, type, seat_height FROM vehicles.motorcycle_body_node
    """)

    # Возвращаем FK у trim/spec на старые таблицы.
    op.drop_constraint('car_spec_engine_id_fkey', 'car_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint('car_spec_transmission_id_fkey', 'car_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('car_spec_engine_id_fkey', 'car_spec', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key('car_spec_transmission_id_fkey', 'car_spec', 'car_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint('car_trim_engine_id_fkey', 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint('car_trim_transmission_id_fkey', 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint('car_trim_body_id_fkey', 'car_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('car_trim_engine_id_fkey', 'car_trim', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('car_trim_transmission_id_fkey', 'car_trim', 'car_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('car_trim_body_id_fkey', 'car_trim', 'car_body', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint('motorcycle_spec_engine_id_fkey', 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint('motorcycle_spec_transmission_id_fkey', 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('motorcycle_spec_engine_id_fkey', 'motorcycle_spec', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key('motorcycle_spec_transmission_id_fkey', 'motorcycle_spec', 'motorcycle_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint('motorcycle_trim_engine_id_fkey', 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint('motorcycle_trim_transmission_id_fkey', 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint('motorcycle_trim_body_id_fkey', 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key('motorcycle_trim_engine_id_fkey', 'motorcycle_trim', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('motorcycle_trim_transmission_id_fkey', 'motorcycle_trim', 'motorcycle_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key('motorcycle_trim_body_id_fkey', 'motorcycle_trim', 'motorcycle_body', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')

    op.drop_table('reminder_node_link', schema='vehicles')
    op.drop_index('engine_node_concern_name_volume_power_unique', table_name='engine_node', schema='vehicles', postgresql_where=sa.text('concern_id IS NOT NULL'))
    op.drop_index('engine_node_brand_name_volume_power_unique', table_name='engine_node', schema='vehicles', postgresql_where=sa.text('brand_id IS NOT NULL'))
    op.drop_table('engine_node', schema='vehicles')
    op.drop_table('user_vehicle_node', schema='vehicles')
    op.drop_table('motorcycle_transmission_node', schema='vehicles')
    op.drop_index('car_transmission_node_concern_type_gears_name_unique', table_name='car_transmission_node', schema='vehicles', postgresql_where=sa.text('concern_id IS NOT NULL'))
    op.drop_index('car_transmission_node_brand_type_gears_name_unique', table_name='car_transmission_node', schema='vehicles', postgresql_where=sa.text('brand_id IS NOT NULL'))
    op.drop_table('car_transmission_node', schema='vehicles')
    op.drop_table('motorcycle_body_node', schema='vehicles')
    op.drop_table('car_body_node', schema='vehicles')
    op.drop_table('vehicle_node', schema='vehicles')
    # ### end Alembic commands ###
