"""migration

Revision ID: ddb4fd70080c
Revises: 4a2b3c5d6e7f
Create Date: 2026-05-18 03:35:07.519007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb4fd70080c'
down_revision: Union[str, None] = '4a2b3c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='accounts')
    op.create_unique_constraint(None, 'user_session', ['token_jti'], schema='accounts')
    op.drop_constraint(op.f('car_spec_vehicle_id_fkey'), 'car_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_spec_generation_id_fkey'), 'car_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'car_spec', 'vehicle', ['vehicle_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'car_spec', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('car_transmission_concern_id_fkey'), 'car_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_transmission_brand_id_fkey'), 'car_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'car_transmission', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'car_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('car_trim_engine_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_trim_transmission_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_trim_generation_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('car_trim_body_id_fkey'), 'car_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'car_trim', 'car_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'car_trim', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'car_trim', 'car_body', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'car_trim', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('motorcycle_spec_vehicle_id_fkey'), 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_spec_generation_id_fkey'), 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'motorcycle_spec', 'vehicle', ['vehicle_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'motorcycle_spec', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('motorcycle_transmission_concern_id_fkey'), 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_transmission_brand_id_fkey'), 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'motorcycle_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'motorcycle_transmission', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('motorcycle_trim_body_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_trim_transmission_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_trim_generation_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('motorcycle_trim_engine_id_fkey'), 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'motorcycle_trim', 'motorcycle_body', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'motorcycle_trim', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'motorcycle_trim', 'motorcycle_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'motorcycle_trim', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('user_vehicle_vehicle_id_fkey'), 'user_vehicle', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('user_vehicle_user_id_fkey'), 'user_vehicle', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'user_vehicle', 'vehicle', ['vehicle_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_vehicle', 'user', ['user_id'], ['id'], source_schema='vehicles', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_country_id_fkey'), 'vehicle', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_brand_country_id_fkey'), 'vehicle_brand', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicle_brand_concern_id_fkey'), 'vehicle_brand', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_brand', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'vehicle_brand', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_concern_country_id_fkey'), 'vehicle_concern', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_concern', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_engine_concern_id_fkey'), 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicle_engine_phase_regulator_system_id_fkey'), 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicle_engine_brand_id_fkey'), 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_engine_phase_regulator_system', ['phase_regulator_system_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_engine_phase_regulator_system_concern_id_fkey'), 'vehicle_engine_phase_regulator_system', schema='vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicle_engine_phase_regulator_system_brand_id_fkey'), 'vehicle_engine_phase_regulator_system', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_engine_phase_regulator_system', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.create_foreign_key(None, 'vehicle_engine_phase_regulator_system', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_generation_series_id_fkey'), 'vehicle_generation', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_generation', 'vehicle_series', ['series_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_group_user_id_fkey'), 'vehicle_group', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_group', 'user', ['user_id'], ['id'], source_schema='vehicles', referent_schema='accounts', ondelete='CASCADE')
    op.drop_constraint(op.f('vehicle_series_brand_id_fkey'), 'vehicle_series', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_series', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_series', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_series_brand_id_fkey'), 'vehicle_series', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'vehicle_group', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_group_user_id_fkey'), 'vehicle_group', 'user', ['user_id'], ['id'], source_schema='vehicles', referent_schema='accounts')
    op.drop_constraint(None, 'vehicle_generation', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_generation_series_id_fkey'), 'vehicle_generation', 'vehicle_series', ['series_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'vehicle_engine_phase_regulator_system', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_engine_phase_regulator_system', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_engine_phase_regulator_system_brand_id_fkey'), 'vehicle_engine_phase_regulator_system', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(op.f('vehicle_engine_phase_regulator_system_concern_id_fkey'), 'vehicle_engine_phase_regulator_system', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_engine_brand_id_fkey'), 'vehicle_engine', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(op.f('vehicle_engine_phase_regulator_system_id_fkey'), 'vehicle_engine', 'vehicle_engine_phase_regulator_system', ['phase_regulator_system_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(op.f('vehicle_engine_concern_id_fkey'), 'vehicle_engine', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(None, 'vehicle_concern', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_concern_country_id_fkey'), 'vehicle_concern', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo', ondelete='SET NULL')
    op.drop_constraint(None, 'vehicle_brand', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_brand', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_brand_concern_id_fkey'), 'vehicle_brand', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(op.f('vehicle_brand_country_id_fkey'), 'vehicle_brand', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo')
    op.drop_constraint(None, 'vehicle', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_country_id_fkey'), 'vehicle', 'country', ['country_id'], ['id'], source_schema='vehicles', referent_schema='geo', ondelete='SET NULL')
    op.drop_constraint(None, 'user_vehicle', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'user_vehicle', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('user_vehicle_user_id_fkey'), 'user_vehicle', 'user', ['user_id'], ['id'], source_schema='vehicles', referent_schema='accounts')
    op.create_foreign_key(op.f('user_vehicle_vehicle_id_fkey'), 'user_vehicle', 'vehicle', ['vehicle_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'motorcycle_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('motorcycle_trim_engine_id_fkey'), 'motorcycle_trim', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('motorcycle_trim_generation_id_fkey'), 'motorcycle_trim', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('motorcycle_trim_transmission_id_fkey'), 'motorcycle_trim', 'motorcycle_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('motorcycle_trim_body_id_fkey'), 'motorcycle_trim', 'motorcycle_body', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'motorcycle_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('motorcycle_transmission_brand_id_fkey'), 'motorcycle_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(op.f('motorcycle_transmission_concern_id_fkey'), 'motorcycle_transmission', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(None, 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'motorcycle_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('motorcycle_spec_generation_id_fkey'), 'motorcycle_spec', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('motorcycle_spec_vehicle_id_fkey'), 'motorcycle_spec', 'vehicle', ['vehicle_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'car_trim', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'car_trim', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('car_trim_body_id_fkey'), 'car_trim', 'car_body', ['body_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('car_trim_generation_id_fkey'), 'car_trim', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('car_trim_transmission_id_fkey'), 'car_trim', 'car_transmission', ['transmission_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('car_trim_engine_id_fkey'), 'car_trim', 'vehicle_engine', ['engine_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'car_transmission', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'car_transmission', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('car_transmission_brand_id_fkey'), 'car_transmission', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(op.f('car_transmission_concern_id_fkey'), 'car_transmission', 'vehicle_concern', ['concern_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_constraint(None, 'car_spec', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'car_spec', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('car_spec_generation_id_fkey'), 'car_spec', 'vehicle_generation', ['generation_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.create_foreign_key(op.f('car_spec_vehicle_id_fkey'), 'car_spec', 'vehicle', ['vehicle_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.drop_constraint(None, 'user_session', schema='accounts', type_='unique')
    op.alter_column('user_session', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='accounts')
    # ### end Alembic commands ###
