"""add VehicleEnginePhaseRegulatorSystem

Revision ID: f5a1b60cc108
Revises: 9ce11073c8a2
Create Date: 2025-10-28 18:47:11.418640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a1b60cc108'
down_revision: Union[str, None] = '9ce11073c8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_engine_phase_regulator_system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phase_regulator_type', sa.SmallInteger(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('concern_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicles.vehicle_brand.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concern_id'], ['vehicles.vehicle_concern.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.add_column('vehicle_engine', sa.Column('phase_regulator_type', sa.SmallInteger(), nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('phase_regulator_system_id', sa.UUID(), nullable=True), schema='vehicles')
    op.alter_column('vehicle_engine', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='vehicles')
    op.drop_constraint(op.f('vehicle_engine_brand_id_fkey'), 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_engine_phase_regulator_system', ['phase_regulator_system_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.create_foreign_key(None, 'vehicle_engine', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles', ondelete='SET NULL')
    op.drop_column('vehicle_engine', 'phase_regulator', schema='vehicles')
    op.drop_column('vehicle_engine', 'phase_regulator_system', schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_engine', sa.Column('phase_regulator_system', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='vehicles')
    op.add_column('vehicle_engine', sa.Column('phase_regulator', sa.SMALLINT(), autoincrement=False, nullable=True), schema='vehicles')
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_engine', schema='vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_engine_brand_id_fkey'), 'vehicle_engine', 'vehicle_brand', ['brand_id'], ['id'], source_schema='vehicles', referent_schema='vehicles')
    op.alter_column('vehicle_engine', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='vehicles')
    op.drop_column('vehicle_engine', 'phase_regulator_system_id', schema='vehicles')
    op.drop_column('vehicle_engine', 'phase_regulator_type', schema='vehicles')
    op.drop_table('vehicle_engine_phase_regulator_system', schema='vehicles')
    # ### end Alembic commands ###
